apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

patchesStrategicMerge:
  - update-replicas.yml
  - use-configmap.yml

configMapGenerator:
  -  name: demo-config
     files:
       - application-qa.yml