apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-app
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  strategy: {}
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - image: demo
        name: demo
        imagePullPolicy: Never
        resources:
          limits:
            memory: 512M
            cpu: 1000m
